### ISSUE TITLE
zcrm-oauth2 -f auth.json command issue

### ISSUE THREAD

**Issue by Nayanika15** [crmpartners/zcrm-oauth2#12]
I am getting the results same as zcrm-oauth2 -h for command zcrm-oauth2 -f auth.json

**Comment by killimouna** [comment]
Same here, this is broken

**Comment by tonylukasavage** [comment]
same here

**Comment by tonylukasavage** [comment]
https://github.com/crmpartners/zcrm-oauth2/blob/a2024d2218f01fcf3b2be4ea289ec43edad9ef2a/ZCRMOAuth2.js#L45

This is the problem. There's a check to make sure `program.args.length` isn't zero, but this command takes no args, only options, so this always fails.
